# Generated by Django 5.0.7 on 2024-08-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Shirt', 'shirt'), ('Tshirt', 'tshirt'), ('Jeans', 'jeans'), ('Short', 'short'), ('Shoes', 'shoes'), ('Hoodie', 'hoodie'), ('Accessories', 'accessories')], max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('price', models.CharField(max_length=10)),
                ('img', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
