# Generated by Django 5.0.7 on 2024-08-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snitch', '0002_rename_img_product_cover_product_img2_product_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='istrend',
            field=models.BooleanField(default=False),
        ),
    ]
