# Generated by Django 5.0.7 on 2024-08-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snitch', '0003_product_istrend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirt', 'shirt'), ('tshirt', 'tshirt'), ('jeans', 'jeans'), ('short', 'short'), ('shoes', 'shoes'), ('hoodie', 'hoodie'), ('accessories', 'accessories')], max_length=50),
        ),
    ]
